name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Build application
      run: go build

    - name: Run tests
      run: go test -v ./...

    - name: Static code analysis
      uses: reviewdog/action-reviewdog@v1
      with:
        tool_name: golint,gosec
        reporter: github-pr-review # Use "github-pr-check" for checks instead of reviews
        github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: kubectl apply -f kubernetes/deployment.yaml

    - name: Check deployment status
      run: kubectl rollout status deployment/olintes-deployment
